#!/usr/bin/env python3

"""
Shared force-field configuration for dock-postprocess.

This module is intentionally used by both minimization and MD so that
protein, ligand, water, and ion parameterization cannot silently diverge
between simulation stages.

Supported protein presets
-------------------------
ff14SB
ff19SB
ff15ipq
amber14-all
amber19-all

Supported ligand backends
-------------------------
OpenFF/SMIRNOFF force fields installed through openmmforcefields
GAFF force fields installed through openmmforcefields

Supported Amber water/ion parameter sets
----------------------------------------
tip3p
tip3pfb
tip4pew
tip4pfb
spce
opc
opc3

The "modeller_model" associated with each water model controls only the
initial solvent topology generated by OpenMM Modeller.addSolvent().  The
requested XML file supplies the actual force-field parameters.
"""

from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path
import re

import openmm.app as app

from openmm.app import ForceField

from openmmforcefields.generators import (
    GAFFTemplateGenerator,
    SMIRNOFFTemplateGenerator,
)


DEFAULT_PROTEIN_FORCEFIELD = "ff14SB"
DEFAULT_LIGAND_FORCEFIELD = "openff-2.3.0"
DEFAULT_WATER_MODEL = "tip3p"


# ============================================================
# DATA CLASSES
# ============================================================

@dataclass(frozen=True)
class ProteinForceFieldSpec:
    name: str
    xml: str
    family: str


@dataclass(frozen=True)
class WaterModelSpec:
    name: str
    family: str
    xml: str

    # Value accepted by Modeller.addSolvent(model=...).
    #
    # For parameter sets that use the same three-site or four-site
    # topology as one of OpenMM's built-in solvent builders, this is
    # the topology-building model only.  Parameters still come from
    # the requested XML above.
    modeller_model: str

    sites: int


@dataclass(frozen=True)
class LigandForceFieldSpec:
    name: str
    backend: str


@dataclass(frozen=True)
class ForceFieldSelection:
    protein: ProteinForceFieldSpec
    ligand: LigandForceFieldSpec
    water: WaterModelSpec

    @property
    def xmls(self) -> list[str]:

        return [
            self.protein.xml,
            self.water.xml,
        ]


# ============================================================
# PROTEIN FORCE FIELDS
# ============================================================

PROTEIN_FORCEFIELDS = {
    "ff14sb":
        ProteinForceFieldSpec(
            name="ff14SB",
            xml="amber14/protein.ff14SB.xml",
            family="amber14",
        ),

    "ff19sb":
        ProteinForceFieldSpec(
            name="ff19SB",
            xml="amber19/protein.ff19SB.xml",
            family="amber19",
        ),

    "ff15ipq":
        ProteinForceFieldSpec(
            name="ff15ipq",
            xml="amber14/protein.ff15ipq.xml",
            family="amber14",
        ),

    "amber14-all":
        ProteinForceFieldSpec(
            name="amber14-all",
            xml="amber14-all.xml",
            family="amber14",
        ),

    "amber19-all":
        ProteinForceFieldSpec(
            name="amber19-all",
            xml="amber19-all.xml",
            family="amber19",
        ),
}


PROTEIN_ALIASES = {
    "amber14":
        "ff14sb",

    "amber14sb":
        "ff14sb",

    "amber14-ff14sb":
        "ff14sb",

    "amber19":
        "ff19sb",

    "amber19sb":
        "ff19sb",

    "amber19-ff19sb":
        "ff19sb",

    "ff15ipq":
        "ff15ipq",
}


# ============================================================
# WATER / ION MODELS
# ============================================================

#
# amber14/ and amber19/ solvent XML files are equivalent in the
# OpenMM distribution currently used here.  We nevertheless select
# the XML belonging to the protein-family namespace for clarity and
# future compatibility.
#
# Modeller.addSolvent() does not accept every parameter-set name.
# The modeller_model entry therefore identifies the appropriate
# topology family:
#
#   TIP3P-FB -> three-site TIP3P topology
#   OPC3     -> three-site TIP3P topology
#   TIP4P-FB -> four-site TIP4P-Ew topology
#   OPC      -> four-site TIP4P-Ew topology
#
# The force-field XML, not modeller_model, determines the final
# water parameters.
#

WATER_MODELS = {
    "tip3p": {
        "modeller_model":
            "tip3p",

        "sites":
            3,
    },

    "tip3pfb": {
        "modeller_model":
            "tip3p",

        "sites":
            3,
    },

    "spce": {
        "modeller_model":
            "spce",

        "sites":
            3,
    },

    "opc3": {
        "modeller_model":
            "tip3p",

        "sites":
            3,
    },

    "tip4pew": {
        "modeller_model":
            "tip4pew",

        "sites":
            4,
    },

    "tip4pfb": {
        "modeller_model":
            "tip4pew",

        "sites":
            4,
    },

    "opc": {
        "modeller_model":
            "tip4pew",

        "sites":
            4,
    },
}


WATER_ALIASES = {
    "tip3p-fb":
        "tip3pfb",

    "tip4p-ew":
        "tip4pew",

    "tip4p-fb":
        "tip4pfb",

    "spc/e":
        "spce",

    "spc-e":
        "spce",

    "opc-3":
        "opc3",
}


# ============================================================
# LIGAND FORCE FIELDS
# ============================================================

LIGAND_ALIASES = {
    "openff":
        DEFAULT_LIGAND_FORCEFIELD,

    "sage":
        DEFAULT_LIGAND_FORCEFIELD,

    "sage-2.3.0":
        "openff-2.3.0",
}


# ============================================================
# HELPERS
# ============================================================

def _normalize(
    value: str,
) -> str:

    return (
        str(
            value
        )
        .strip()
        .lower()
    )


def openmm_data_directory() -> Path:

    return (
        Path(
            app.__file__
        )
        .resolve()
        .parent
        / "data"
    )


def forcefield_xml_exists(
    xml: str,
) -> bool:

    return (
        openmm_data_directory()
        / xml
    ).exists()


# ============================================================
# PROTEIN RESOLUTION
# ============================================================

def resolve_protein_forcefield(
    name: str | None,
) -> ProteinForceFieldSpec:

    if name is None:

        name = (
            DEFAULT_PROTEIN_FORCEFIELD
        )


    key = _normalize(
        name
    )


    key = PROTEIN_ALIASES.get(
        key,
        key,
    )


    if key not in PROTEIN_FORCEFIELDS:

        choices = ", ".join(
            sorted(
                spec.name
                for spec
                in PROTEIN_FORCEFIELDS.values()
            )
        )


        raise ValueError(
            "Unsupported protein force field "
            f"'{name}'. Supported presets: {choices}"
        )


    spec = (
        PROTEIN_FORCEFIELDS[
            key
        ]
    )


    if not forcefield_xml_exists(
        spec.xml
    ):

        raise RuntimeError(
            "Required OpenMM force-field XML is not installed:\n"
            f"  {spec.xml}"
        )


    return spec


# ============================================================
# WATER RESOLUTION
# ============================================================

def resolve_water_model(
    name: str | None,
    protein_family: str,
) -> WaterModelSpec:

    if name is None:

        name = (
            DEFAULT_WATER_MODEL
        )


    key = _normalize(
        name
    )


    key = WATER_ALIASES.get(
        key,
        key,
    )


    if key not in WATER_MODELS:

        choices = ", ".join(
            sorted(
                WATER_MODELS
            )
        )


        raise ValueError(
            "Unsupported water model "
            f"'{name}'. Supported models: {choices}"
        )


    if protein_family not in {
        "amber14",
        "amber19",
    }:

        raise ValueError(
            "Amber water/ion presets currently require an "
            "Amber14 or Amber19 protein-family preset."
        )


    data = (
        WATER_MODELS[
            key
        ]
    )


    xml = (
        f"{protein_family}/{key}.xml"
    )


    if not forcefield_xml_exists(
        xml
    ):

        raise RuntimeError(
            "Required OpenMM water/ion XML is not installed:\n"
            f"  {xml}"
        )


    return WaterModelSpec(
        name=key,
        family=protein_family,
        xml=xml,
        modeller_model=(
            data[
                "modeller_model"
            ]
        ),
        sites=int(
            data[
                "sites"
            ]
        ),
    )


# ============================================================
# LIGAND RESOLUTION
# ============================================================

def installed_openff_forcefields() -> tuple[str, ...]:

    return tuple(
        SMIRNOFFTemplateGenerator
        .INSTALLED_FORCEFIELDS
    )


def installed_gaff_forcefields() -> tuple[str, ...]:

    return tuple(
        GAFFTemplateGenerator
        .INSTALLED_FORCEFIELDS
    )


def resolve_ligand_forcefield(
    name: str | None,
) -> LigandForceFieldSpec:

    if name is None:

        name = (
            DEFAULT_LIGAND_FORCEFIELD
        )


    key = _normalize(
        name
    )


    key = LIGAND_ALIASES.get(
        key,
        key,
    )


    openff_installed = {
        _normalize(
            value
        ):
        value

        for value
        in installed_openff_forcefields()
    }


    gaff_installed = {
        _normalize(
            value
        ):
        value

        for value
        in installed_gaff_forcefields()
    }


    if key in openff_installed:

        return LigandForceFieldSpec(
            name=(
                openff_installed[
                    key
                ]
            ),
            backend="smirnoff",
        )


    if key in gaff_installed:

        return LigandForceFieldSpec(
            name=(
                gaff_installed[
                    key
                ]
            ),
            backend="gaff",
        )


    all_installed = (
        sorted(
            openff_installed.values()
        )
        + sorted(
            gaff_installed.values()
        )
    )


    raise ValueError(
        "Ligand force field is not installed: "
        f"'{name}'.\n"
        "Installed ligand force fields:\n  "
        + "\n  ".join(
            all_installed
        )
    )


# ============================================================
# COMPLETE SELECTION
# ============================================================

def resolve_forcefield_selection(
    protein_forcefield: str | None = None,
    ligand_forcefield: str | None = None,
    water_model: str | None = None,
) -> ForceFieldSelection:

    protein = resolve_protein_forcefield(
        protein_forcefield
    )


    ligand = resolve_ligand_forcefield(
        ligand_forcefield
    )


    water = resolve_water_model(
        water_model,
        protein.family,
    )


    return ForceFieldSelection(
        protein=protein,
        ligand=ligand,
        water=water,
    )


# ============================================================
# FORCEFIELD CONSTRUCTION
# ============================================================

def register_ligand_template_generator(
    forcefield: ForceField,
    offmol,
    ligand_spec: LigandForceFieldSpec,
):

    if ligand_spec.backend == "smirnoff":

        generator = (
            SMIRNOFFTemplateGenerator(
                molecules=offmol,
                forcefield=(
                    ligand_spec.name
                ),
            )
        )


    elif ligand_spec.backend == "gaff":

        generator = (
            GAFFTemplateGenerator(
                molecules=offmol,
                forcefield=(
                    ligand_spec.name
                ),
            )
        )


    else:

        raise RuntimeError(
            "Internal error: unknown ligand force-field "
            f"backend '{ligand_spec.backend}'."
        )


    forcefield.registerTemplateGenerator(
        generator.generator
    )


    return generator


def create_forcefield(
    offmol,
    protein_forcefield: str | None = None,
    ligand_forcefield: str | None = None,
    water_model: str | None = None,
):

    selection = (
        resolve_forcefield_selection(
            protein_forcefield=(
                protein_forcefield
            ),
            ligand_forcefield=(
                ligand_forcefield
            ),
            water_model=(
                water_model
            ),
        )
    )


    forcefield = ForceField(
        *selection.xmls
    )


    generator = (
        register_ligand_template_generator(
            forcefield=forcefield,
            offmol=offmol,
            ligand_spec=(
                selection.ligand
            ),
        )
    )


    return (
        forcefield,
        selection,
        generator,
    )


# ============================================================
# REPORTING
# ============================================================

def describe_forcefield_selection(
    selection: ForceFieldSelection,
):

    print()
    print("=" * 80)
    print("FORCE-FIELD SELECTION")
    print("=" * 80)

    print(
        "Protein:"
    )

    print(
        f"  preset: {selection.protein.name}"
    )

    print(
        f"  XML:    {selection.protein.xml}"
    )


    print()
    print(
        "Ligand:"
    )

    print(
        f"  force field: {selection.ligand.name}"
    )

    print(
        f"  backend:     {selection.ligand.backend}"
    )


    print()
    print(
        "Water / ions:"
    )

    print(
        f"  model:         {selection.water.name}"
    )

    print(
        f"  XML:           {selection.water.xml}"
    )

    print(
        f"  topology type: {selection.water.modeller_model}"
    )

    print(
        f"  interaction sites: {selection.water.sites}"
    )


def available_forcefields_text() -> str:

    lines = []


    lines.append(
        "Protein presets:"
    )


    for spec in sorted(
        PROTEIN_FORCEFIELDS.values(),
        key=lambda value:
            value.name.lower(),
    ):

        lines.append(
            f"  {spec.name:12s}  {spec.xml}"
        )


    lines.append(
        ""
    )

    lines.append(
        "Water models:"
    )


    for name in sorted(
        WATER_MODELS
    ):

        lines.append(
            f"  {name}"
        )


    lines.append(
        ""
    )

    lines.append(
        "Installed OpenFF force fields:"
    )


    for name in (
        installed_openff_forcefields()
    ):

        lines.append(
            f"  {name}"
        )


    lines.append(
        ""
    )

    lines.append(
        "Installed GAFF force fields:"
    )


    for name in (
        installed_gaff_forcefields()
    ):

        lines.append(
            f"  {name}"
        )


    return "\n".join(
        lines
    )
